import * as tmdb from '@lorenzopant/tmdb'

// Object.getOwnPropertyDescriptor

console.log(Object.getOwnPropertyNames(tmdb))

const C = {
    AUTHENTICATION: {
      VALIDATE: `/authentication`,
      GUEST_SESSION: `/authentication/guest_session/new`,
      REQUEST_TOKEN: `/authentication/token/new`,
      CREATE_SESSION: `/authentication/session/new`,
      CREATE_SESSION_WITH_LOGIN: `/authentication/token/validate_with_login`,
      DELETE_SESSION: `/authentication/session`,
    },
    ACCOUNT: {
      DETAILS: `/account`,
      ADD_FAVORITE: `/favorite`,
      ADD_TO_WATCHLIST: `/watchlist`,
      FAVORITE_MOVIES: `/favorite/movies`,
      FAVORITE_TV: `/favorite/tv`,
      WATCHLIST_MOVIES: `/watchlist/movies`,
      WATCHLIST_TV: `/watchlist/tv`,
      RATED_MOVIES: `/rated/movies`,
      RATED_TV: `/rated/tv`,
      RATED_TV_EPISODES: `/rated/tv/episodes`,
      LISTS: `/lists`,
    },
    CONFIGURATION: {
      DETAILS: `/configuration`,
      COUNTRIES: `/configuration/countries`,
      JOBS: `/configuration/jobs`,
      LANGUAGES: `/configuration/languages`,
      TIMEZONES: `/configuration/timezones`,
      PRIMARY_TRANSLATIONS: `/configuration/primary_translations`,
    },
    CERTIFICATIONS: { MOVIE_CERTIFICATIONS: `/certification/movie/list`, TV_CERTIFICATIONS: `/certification/tv/list` },
    CHANGES: { MOVIE_LIST: `/movie/changes`, PEOPLE_LIST: `/person/changes`, TV_LIST: `/tv/changes` },
    DISCOVER: { MOVIE: `/discover/movie`, TV: `/discover/tv` },
    FIND: `/find`,
    CREDITS: { DETAILS: `/credit` },
    COMPANIES: { DETAILS: `/company`, ALTERNATIVE_NAMES: `/alternative_names`, IMAGES: `/images` },
    COLLECTIONS: { DETAILS: `/collection`, IMAGES: `/images`, TRANSLATIONS: `/translations` },
    GENRES: { MOVIE_LIST: `/genre/movie/list`, TV_LIST: `/genre/tv/list` },
    KEYWORDS: { DETAILS: `/keyword`, MOVIES: `/movies` },
    MOVIES: {
      DETAILS: `/movie`,
      ALTERNATIVE_TITLES: `/alternative_titles`,
      CREDITS: `/credits`,
      EXTERNAL_IDS: `/external_ids`,
      KEYWORDS: `/keywords`,
      CHANGES: `/changes`,
      IMAGES: `/images`,
      LATEST: `/latest`,
      NOW_PLAYING: `/now_playing`,
      POPULAR: `/popular`,
      RECOMMENDATIONS: `/recommendations`,
      RELEASE_DATES: `/release_dates`,
      REVIEWS: `/reviews`,
      SIMILAR: `/similar`,
      TOP_RATED: `/top_rated`,
      TRANSLATIONS: `/translations`,
      UPCOMING: `/upcoming`,
      VIDEOS: `/videos`,
      WATCH_PROVIDERS: `/watch/providers`,
    },
    NETWORKS: { DETAILS: `/network`, ALTERNATIVE_NAMES: `/alternative_names`, IMAGES: `/images` },
    PEOPLE: {
      DETAILS: `/person`,
      CHANGES: `/changes`,
      COMBINED_CREDITS: `/combined_credits`,
      EXTERNAL_IDS: `/external_ids`,
      IMAGES: `/images`,
      LATEST: `/latest`,
      MOVIE_CREDITS: `/movie_credits`,
      TAGGED_IMAGES: `/tagged_images`,
      TRANSLATIONS: `/translations`,
      TV_CREDITS: `/tv_credits`,
    },
    SEARCH: {
      MOVIE: `/search/movie`,
      COLLECTION: `/search/collection`,
      COMPANY: `/search/company`,
      KEYWORD: `/search/keyword`,
      MULTI: `/search/multi`,
      PERSON: `/search/person`,
      TV: `/search/tv`,
    },
    TV_SERIES: {
      DETAILS: `/tv`,
      AGGREGATE_CREDITS: `/aggregate_credits`,
      AIRING_TODAY: `/airing_today`,
      ALTERNATIVE_TITLES: `/alternative_titles`,
      CHANGES: `/changes`,
      CONTENT_RATINGS: `/content_ratings`,
      CREDITS: `/credits`,
      EPISODE_GROUPS: `/episode_groups`,
      EXTERNAL_IDS: `/external_ids`,
      IMAGES: `/images`,
      KEYWORDS: `/keywords`,
      LATEST: `/latest`,
      LISTS: `/lists`,
      ON_THE_AIR: `/on_the_air`,
      POPULAR: `/popular`,
      RECOMMENDATIONS: `/recommendations`,
      REVIEWS: `/reviews`,
      SCREENED_THEATRICALLY: `/screened_theatrically`,
      SIMILAR: `/similar`,
      TOP_RATED: `/top_rated`,
      TRANSLATIONS: `/translations`,
      VIDEOS: `/videos`,
      WATCH_PROVIDERS: `/watch/providers`,
    },
    TV_SEASONS: {
      DETAILS: `/season`,
      AGGREGATE_CREDITS: `/aggregate_credits`,
      CHANGES: `/changes`,
      CREDITS: `/credits`,
      EXTERNAL_IDS: `/external_ids`,
      IMAGES: `/images`,
      TRANSLATIONS: `/translations`,
      VIDEOS: `/videos`,
      WATCH_PROVIDERS: `/watch/providers`,
    },
    TV_EPISODES: {
      DETAILS: `/episode`,
      CHANGES: `/changes`,
      CREDITS: `/credits`,
      EXTERNAL_IDS: `/external_ids`,
      IMAGES: `/images`,
      TRANSLATIONS: `/translations`,
      VIDEOS: `/videos`,
    },
    TV_EPISODE_GROUPS: { DETAILS: `/tv/episode_group` },
    WATCH_PROVIDERS: { MOVIE: `/watch/providers/movie`, TV: `/watch/providers/tv`, REGIONS: `/watch/providers/regions` },
    TRENDING: { ALL: `/trending/all`, MOVIE: `/trending/movie`, TV: `/trending/tv`, PERSON: `/trending/person` },
    REVIEWS: { DETAILS: `/review` },
    PEOPLE_LISTS: { POPULAR: `/person/popular` },
    LISTS: { DETAILS: `/list`, ADD_ITEM: `/add_item`, ITEM_STATUS: `/item_status`, CLEAR: `/clear`, REMOVE_ITEM: `/remove_item` },
    GUEST_SESSIONS: { DETAILS: `/guest_session`, RATED_MOVIES: `/rated/movies`, RATED_TV: `/rated/tv`, RATED_TV_EPISODES: `/rated/tv/episodes` },
  },
  w = {
    AUTH: { REQUEST_TOKEN: `/auth/request_token`, ACCESS_TOKEN: `/auth/access_token` },
    ACCOUNT: {
      DETAILS: `/account`,
      LISTS: `/lists`,
      FAVORITE_MOVIES: `/favorite/movies`,
      FAVORITE_TV: `/favorite/tv`,
      WATCHLIST_MOVIES: `/watchlist/movies`,
      WATCHLIST_TV: `/watchlist/tv`,
      RATED_MOVIES: `/rated/movies`,
      RATED_TV: `/rated/tv`,
    },
    LISTS: { DETAILS: `/list`, ITEMS: `/items`, ITEM_STATUS: `/item_status`, CLEAR: `/clear` },
  }
