name: CI

on:
#  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v6
        with:
          version: latest

      - uses: actions/setup-node@v6
        with:
          node-version: latest

      - run: echo "approve-builds=true" >> .npmrc

      - run: rm pnpm-lock.yaml

      - run: pnpm approve-builds -all
 
      - run: pnpm install ---dangerously-allow-all-builds

      - run: pnpm build